=== artnavsegda/zcore/src/schema/firewall/zones.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "zones",
  "description": "Firewall zones list",
  "type": "array",
  "items": {
    "type": "object",
    "title": "Interface entity",
    "required": ["name", "network"],
    "properties": {
      "name": {
        "type": "string",
        "description": "Unique zone name",
        "hidden": true
      },
      "network": {
        "type": "array",
        "items": {
          "type": "string",
          "description": "Interface name",
          "cue": [ "mobile", "ethernet" ],
          "default": "loopback"
        },
        "description": "List of interfaces attached to this zone"
      },
      "masq": {
        "type": "boolean",
        "description": "Specifies whether outgoing zone traffic should be masqueraded"
      },
      "conntack": {
        "type": "boolean",
        "description": "Force connection tracking for this zone"
      },
      "mtu_fix": {
        "type": "boolean",
        "description": "Enable MSS clamping for outgoing zone traffic"
      },
      "input": {
        "type": "string",
        "enum": ["ACCEPT", "DROP", "REJECT"],
        "description": "Default action for INPUT chain",
        "default": "ACCEPT"
      },
      "output": {
        "type": "string",
        "enum": ["ACCEPT", "DROP", "REJECT"],
        "description": "Default action for DROP chain",
        "default": "ACCEPT"
      },
      "forward": {
        "type": "string",
        "enum": ["ACCEPT", "DROP", "REJECT"],
        "description": "Default action for REJECT chain",
        "default": "ACCEPT"
      }
   }
 },
 "commands": {
   "apply": {
     "command": "/home/art/Coding/zcore/src/zfilter2",
     "args": ["zfilter2", "firewall.zones.schema", "./apply.sh"],
     "json": "in"
   },
   "add": {
     "command": "/home/art/Coding/zcore/src/zgen",
     "args": ["zgen", "firewall.zones.schema", "./add.sh"],
     "argpass": true,
     "cue": ["name","network"],
     "json": "out"
   }
 },
 "acquire": {
   "shell": "/home/art/Coding/zcore/src/zfilter",
   "args": ["zfilter", "firewall.zones.schema", "./zones.sh"]
 }
}

=== artnavsegda/zcore/src/json/firewall/zones.json
[
    {
        "name":     "lan",
        "network":  ["vlan1"],
        "input":    "ACCEPT",
        "output":   "ACCEPT",
        "forward":  "ACCEPT"
    },
    {
        "name":     "wan",
        "network":  ["vlan22", "sim2", "sim1"],
        "input":    "REJECT",
        "output":   "ACCEPT",
        "forward":  "ACCEPT",
        "masq":     true
    }
]
